# Enabling HTTPS
server.port: 8443
# The format used for the keystore
server.ssl.key-store-type: PKCS12
# The path to the keystore containing the certificate
server.ssl.key-store: classpath:ssl/thalasoft.keystore
# The password used to generate the certificate
server.ssl.key-store-password: mydearssl
# The alias mapped to the certificate
server.ssl.key-alias: thalasoft.key
server.ssl.key-password: littlep

server.error.whitelabel.enabled: false
server.servlet.context-path: /api

# Logging
logging:
  file: logs/user-rest.log
  level:
    com.thalasoft: debug
    org:
      hibernate:
        SQL: debug
      springframework: debug

# Security 
security.jwt:
  tokenIssuer: http://thalasoft.com
  tokenPrivateKey: xm8EOfkdu4d653D_GGIDAwQus
  accessTokenExpirationTime: 60 # Expressed in minutes
  refreshTokenExpirationTime: 10080 # Expressed in minutes
  allowedClockSkewSeconds: 300
  checkUserScopes: false
  sslKeystoreFilename: oauth2/thalasoft.keystore
  sslKeystorePassword: mydearssl
  sslKeyPair: user-rest.key
  sslPublicKeyFilename: oauth2/thalasoft.pub  

# security: TODO use this or remove it
  # oauth2:
    # resource.filter-order: 3
    # client:
    #   registration:
    #     google:
    #       client-id: <your client id>
    #       client-secret: <your client secret>
    #     facebook:
    #       client-id: <your client id> 
    #       client-secret: <your client secret>

# SSL
# # Define a custom port instead of the default 8080
# server.port=8443
# # Tell Spring Security (if used) to require requests over HTTPS
# security.require-ssl=true
# # The format used for the keystore 
# server.ssl.key-store-type=PKCS12
# # The path to the keystore containing the certificate
# server.ssl.key-store=classpath:keystore.p12
# # The password used to generate the certificate
# server.ssl.key-store-password=password
# # The alias mapped to the certificate
# server.ssl.key-alias=tomcat

# Actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info,health,httptrace
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      roles: ENDPOINT_ADMIN, ADMIN, USER
      show-details: when-authorized # always
    httptrace:
      enabled: true
  info:
    git:
      mode:
        full
